version: "2"

services:
  lancache-dns:
    image: lancache/lancache-dns:latest
    environment:
      - USE_GENERIC_CACHE=true
      - LANCACHE_IP=$HOST_IP
    ports:
      - 53:53/udp
  sniproxy:
    image: lancache/sniproxy:latest
    restart: unless-stopped
    depends_on:
      - lancache-dns
    ports:
      - 443:443
  lancache:
    image: lancache/monolithic:latest
    restart: unless-stopped
    depends_on:
      - sniproxy
    environment:
      - CACHE_MEM_SIZE 6000m
      - CACHE_DISK_SIZE 65000m
      - CACHE_MAX_AGE 14d
    volumes:
      - ./cache/data:/data/cache
      - ./cache/logs:/data/logs
    ports:
      - 80:80
